### PR TITLE
nvidia/pgi port

### PR DESCRIPTION
**Pull request by ajmay81**
A few changes so the code builds with nvfortran 20.9

### CODE REVIEW

**Review by awvwgk — COMMENTED** [review]
This should be fixed by adding the compiler arguments `-Mallocatable=03` and `-Mbackslash` in the meson.build file instead, or at configure time by adding the arguments with `-Dfortran_args`

**Comment by ajmay81** [comment]
Thanks, unfortunately it does not seem to help with the internal compiler error:
```
/opt/nvidia/hpc_sdk/Linux_x86_64/20.9/compilers/bin/pgfortran -c -g -Mallocatable=03 -Mbackslash class_results.f90
Lowering Error: unexpected data type at assignment [ast=251,asttype=17,datatype=0]
Lowering Error: unknown source type for conversion to integer*8 [ast=250,asttype=1,datatype=0]
NVFORTRAN-F-0000-Internal compiler error. Errors in Lowering       2  (class_results.f90: 150)
NVFORTRAN/x86-64 Linux 20.9-0: compilation aborted
```
so I don't think the (`-Mallocatable=03`) compiler option helps in that case.

Personally I try to avoid collecting lists of compiler options because it makes the build files more complicated and it feels always a bit like fighting the default behaviour, but I do understand it is a matter of personal taste.

**Comment by awvwgk** [comment]
Sigh, another lowering error, I would suggest to report to upstream and hope they manage to fix the buggy front-end on their side: https://forums.developer.nvidia.com/c/accelerated-computing/hpc-compilers/nvc-nvc-and-nvfortran/313. We can implement the workaround to have at least something working in the mean-time.

At least for some part I would prefer to have somewhat predictable behavior across compiler vendors, standard compliant code should compile regardless of their set of useful extension, the backslash feature of NVHPC / PGI is non-standard and I don't want to risk accidentally using it in the code base.

**Comment by awvwgk** [comment]
I created a minimal working example, seems to be related to a deferred length character in a repeat intrinsic:

```f90
character(len=:), allocatable :: output
call a_proc(output)
contains
subroutine a_proc(str)
   character(len=:), allocatable, intent(in) :: str
   if (allocated(str)) then
      write(*, '(a)') repeat(str, 1)
   end if
end subroutine a_proc
end
```

I'll go ahead and report the issue to upstream.

**Comment by ajmay81** [comment]
Thanks very much. My real interest with this compiler is that it's front end is supposedly closely aligned with the new llvm flang and so I'm hoping by keeping as much as possible working with nvfortran then we'll be in good shape for when flang is ready as a standalone compiler.

Do you want me to update this PR removing the backslash changes, or do you want to take it from here?

**Comment by awvwgk** [comment]
Interesting, I'm not sure what the actual status of `flang` is right now and if it can actually be used in production. I guess you are talking about the `f18` front-end now known as LLVM `flang` rather than the classic `flang` based on the PGI compilers?

If there is finally a package of whatever `flang` out for the major distros (allowing to setup a CI environment), I will happily make all my projects compatible with this compiler, unless this is the case, I don't think it is worth pursuing such efforts, because I can't keep the projects from breaking compatibility again.

**Comment by ajmay81** [comment]
That's right, llvm made their first release containing a flang just recently, but it's only the front end: https://releases.llvm.org/11.0.0/tools/flang/docs/ReleaseNotes.html rather than a complete compiler. I had thought since PGI was the major contributor to f18 that they were already using this inside their own compiler, certainly I noticed many problems when updating from pgi 19.10 to 20.x and had assumed it was down to a migration to f18 front end.

I'm not yet aware of any distros including this, opensuse tumbleweed has llvm 11 since a few weeks but they have not packaged the flang component, I guess there is not much point until the compiler doesn't require another compiler to actually compile.

**Comment by awvwgk** [comment]
I'll certainly be looking out for a standalone LLVM `flang`, especially to get it running for the projects over at @fortran-lang.

> Do you want me to update this PR removing the backslash changes, or do you want to take it from here?

Unless there is an actual need to be compatible with the NVHPC compilers (like using accelerators with OpenACC), I would prefer to not work around their bugs. Still, thanks for taking the time to look into the NVHPC compiler issues.

**Comment by ajmay81** [comment]
Okay, thanks for looking at the PR and making the bug report to nvidia.

**Pull request closed without merging**
