### PR TITLE
[doc] Remove duplicated `--version` from man

### PR DESCRIPTION
**Pull request by e-kwsm**
[ci skip]

### CODE REVIEW

**Comment by e-kwsm** [comment]
Off topic: the following seems to be incorrect
https://github.com/dftd4/dftd4/blob/f3216acdbc305628b27b0876ab5af4671487f981/man1/dftd4.1.txt#L98-L104

On my machine (Debian 10, gfortran 8.3.0), `dftd4` without command line arguments, or Fortran's `error stop`, exits with 1.

Maybe the exit code for error depends on machines/compilers.

**Comment by awvwgk** [comment]
This is indeed compiler dependent, for Intel it always stops with 128, while GNU it is using 1.

**Comment by e-kwsm** [comment]
@awvwgk Thanks for quick reply.

I think EXIT STATUS can be removed as it follows the convention.

**Comment by awvwgk** [comment]
I think, the documentation could use a general overhaul.

**Pull request merged**
