### PR TITLE
Release version 3.7.0

### LINKED ISSUE #255: gfortran 11.4 cannot compile - /usr/bin/ld: cannot find -lFALSE: No such file or directory
The only other issue I found like this is https://github.com/dftd4/dftd4/issues/124, which was blamed on CMake 3.17 or Cray.  I am using GCC 11.4 on an Ubuntu 22 system, so I don't understand the problem.

What should I do to debug this?

```
/tmp$ git clone --recursive https://github.com/dftd4/dftd4.git && cd dftd4 && mkdir build && cd build && cmake .. && cmake --build .
Cloning into 'dftd4'...
remote: Enumerating objects: 2141, done.
remote: Counting objects: 100% (710/710), done.
remote: Compressing objects: 100% (448/448), done.
remote: Total 2141 (delta 558), reused 345 (delta 259), pack-reused 1431 (from 1)
Receiving objects: 100% (2141/2141), 2.09 MiB | 10.82 MiB/s, done.
Resolving deltas: 100% (1459/1459), done.
Submodule 'assets/aur/dftd4' (https://aur.archlinux.org/dftd4.git) registered for path 'assets/aur/dftd4'
Submodule 'assets/aur/dftd4-git' (https://aur.archlinux.org/dftd4-git.git) registered for path 'assets/aur/dftd4-git'
Cloning into '/tmp/dftd4/assets/aur/dftd4'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 26 (delta 2), reused 26 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (26/26), 11.62 KiB | 11.62 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Cloning into '/tmp/dftd4/assets/aur/dftd4-git'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 8 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (8/8), done.
Submodule path 'assets/aur/dftd4': checked out 'a8947fb60f1b6d192046cb91c7c0524fd4470885'
Submodule path 'assets/aur/dftd4-git': checked out '7e92bd04dea45dcba5d127938d55e85f73c6e753'
-- The Fortran compiler identification is GNU 11.4.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/f95 - skipped
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Found OpenMP_Fortran: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libblas.so
-- mctc-lib: Find installed package
-- Could NOT find mctc-lib (missing: mctc-lib_DIR)
-- Retrieving mctc-lib revision v0.3.0 from https://github.com/grimme-lab/mctc-lib
-- mstore: Find installed package
-- Could NOT find mstore (missing: mstore_DIR)
-- Retrieving mstore revision v0.2.0 from https://github.com/grimme-lab/mstore
-- multicharge: Find installed package
-- Could NOT find multicharge (missing: multicharge_DIR)
-- Retrieving multicharge revision HEAD from https://github.com/grimme-lab/multicharge
-- Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done (3.6s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/dftd4/build
[  0%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/env/accuracy.f90.o
[  1%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/env/error.f90.o
[  2%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/env/system.f90.o
[  3%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/env.f90.o
[  3%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/env/testing.f90.o
[  4%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/filetype.f90.o
[  5%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/codata2018.f90.o
[  6%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/constants.f90.o
[  6%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/convert.f90.o
[  7%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/resize.f90.o
[  8%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/structure/info.f90.o
[  9%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/symbols.f90.o
[ 10%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/structure.f90.o
[ 10%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/utils.f90.o
[ 11%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/aims.f90.o
[ 12%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/ctfile.f90.o
[ 12%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/gaussian.f90.o
[ 13%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/genformat.f90.o
[ 14%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/pdb.f90.o
[ 15%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/qchem.f90.o
[ 15%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/qcschema.F90.o
[ 16%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/turbomole.f90.o
[ 16%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/vasp.f90.o
[ 17%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read/xyz.f90.o
[ 17%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/read.f90.o
[ 17%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/aims.f90.o
[ 18%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/ctfile.f90.o
[ 19%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/gaussian.f90.o
[ 20%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/math.f90.o
[ 20%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/genformat.f90.o
[ 21%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/pdb.f90.o
[ 22%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/qchem.f90.o
[ 23%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/version.F90.o
[ 23%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/qcschema.f90.o
[ 24%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/turbomole.f90.o
[ 25%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/vasp.f90.o
[ 25%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write/xyz.f90.o
[ 26%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io/write.f90.o
[ 26%] Building Fortran object _deps/mctc-lib-build/CMakeFiles/mctc-lib-lib.dir/src/mctc/io.f90.o
[ 27%] Linking Fortran static library libmctc-lib.a
[ 27%] Built target mctc-lib-lib
[ 28%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/cutoff.f90.o
[ 29%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/data/covrad.f90.o
[ 30%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/data.f90.o
[ 30%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/blas.F90.o
[ 30%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/ewald.f90.o
[ 31%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/lapack.F90.o
[ 32%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/wignerseitz.f90.o
[ 33%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/model.F90.o
[ 33%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/ncoord.f90.o
[ 33%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/version.f90.o
[ 34%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/output.f90.o
[ 35%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/param/eeq2019.f90.o
[ 36%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge/param.f90.o
[ 37%] Building Fortran object _deps/multicharge-build/CMakeFiles/multicharge-lib.dir/src/multicharge.f90.o
[ 37%] Linking Fortran static library libmulticharge.a
[ 37%] Built target multicharge-lib
[ 38%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/cutoff.f90.o
[ 38%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/damping.f90.o
[ 39%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/damping/atm.f90.o
[ 40%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/data/covrad.f90.o
[ 41%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/data/en.f90.o
[ 41%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/data/hardness.f90.o
[ 42%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/data/r4r2.f90.o
[ 43%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/data/zeff.f90.o
[ 44%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/data.f90.o
[ 44%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/damping/rational.f90.o
[ 44%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/blas.F90.o
[ 45%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/charge.f90.o
[ 46%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/reference.f90.o
[ 46%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/model.f90.o
[ 47%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/ncoord.f90.o
[ 48%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/disp.f90.o
[ 49%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/numdiff.f90.o
[ 49%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/utils.f90.o
[ 50%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/param.f90.o
[ 51%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/version.f90.o
[ 51%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4.f90.o
[ 52%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/api.f90.o
[ 52%] Building Fortran object CMakeFiles/dftd4-lib.dir/src/dftd4/output.f90.o
[ 53%] Linking Fortran static library libdftd4.a
[ 53%] Built target dftd4-lib
[ 54%] Building Fortran object _deps/mctc-lib-build/app/CMakeFiles/mctc-convert.dir/main.f90.o
[ 55%] Linking Fortran executable mctc-convert
[ 55%] Built target mctc-convert
[ 56%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_math.f90.o
[ 56%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read.f90.o
[ 57%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_aims.f90.o
[ 58%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_ctfile.f90.o
[ 58%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_gaussian.f90.o
[ 59%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_genformat.f90.o
[ 60%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_pdb.f90.o
[ 60%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_qchem.f90.o
[ 61%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_qcschema.f90.o
[ 62%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_turbomole.f90.o
[ 62%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_vasp.f90.o
[ 63%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_read_xyz.f90.o
[ 64%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_symbols.f90.o
[ 65%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/testsuite_structure.f90.o
[ 65%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write.f90.o
[ 66%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_aims.f90.o
[ 67%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_ctfile.f90.o
[ 67%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_gaussian.f90.o
[ 68%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_genformat.f90.o
[ 69%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_pdb.f90.o
[ 69%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_qchem.f90.o
[ 70%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_turbomole.f90.o
[ 71%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_vasp.f90.o
[ 71%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/test_write_xyz.f90.o
[ 71%] Building Fortran object _deps/mctc-lib-build/test/CMakeFiles/mctc-lib-tester.dir/main.f90.o
[ 72%] Linking Fortran executable mctc-lib-tester
[ 72%] Built target mctc-lib-tester
[ 73%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/data/record.f90.o
[ 73%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/amino20x4.f90.o
[ 74%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/but14diol.f90.o
[ 74%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/data/collection.f90.o
[ 75%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/data/store.f90.o
[ 76%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/heavy28.f90.o
[ 76%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/ice10.f90.o
[ 77%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/il16.f90.o
[ 78%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/mb16_43.f90.o
[ 78%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/upu23.f90.o
[ 79%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore/x23.f90.o
[ 80%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore.f90.o
[ 80%] Building Fortran object _deps/mstore-build/CMakeFiles/mstore-lib.dir/src/mstore_version.f90.o
[ 81%] Linking Fortran static library libmstore.a
[ 81%] Built target mstore-lib
[ 82%] Building Fortran object _deps/mstore-build/app/fortranize/CMakeFiles/mstore-fortranize.dir/main.f90.o
[ 82%] Linking Fortran executable mstore-fortranize
[ 82%] Built target mstore-fortranize
[ 83%] Building Fortran object _deps/mstore-build/app/info/CMakeFiles/mstore-info.dir/main.f90.o
[ 84%] Linking Fortran executable mstore-info
[ 84%] Built target mstore-info
[ 85%] Building Fortran object _deps/multicharge-build/app/CMakeFiles/multicharge-exe.dir/main.f90.o
[ 85%] Linking Fortran executable multicharge
/usr/bin/ld: cannot find -lFALSE: No such file or directory
collect2: error: ld returned 1 exit status
gmake[2]: *** [_deps/multicharge-build/app/CMakeFiles/multicharge-exe.dir/build.make:101: _deps/multicharge-build/app/multicharge] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:921: _deps/multicharge-build/app/CMakeFiles/multicharge-exe.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```

```
$ cmake --version
cmake version 3.29.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

### PR DESCRIPTION
**Pull request by awvwgk**
Probably needs to wait for #225 

Closes #255

### CODE REVIEW

**Comment by marvinfriede** [comment]
> Probably needs to wait for #225

Agreed. We also planned to wait for the publication of the actinide paper until we make an "official" new release.

**Comment by awvwgk** [comment]
If the paper publication is blocking a minor version release, I would insist on creating patch release by cherry-picking all the bugfixes for now.

**Comment by marvinfriede** [comment]
The paper should not take too long (definitely January), and we could also release after submission. But if the release of the PySCF patch is urgent, I am fine with your suggestion.

**Review by marvinfriede — CHANGES_REQUESTED** [review]
Update: Apparently, there is an error in the actinide parametrization, which requires fixing.

**Review by marvinfriede — APPROVED** [review]

**Comment by aizvorski** [comment]
Hello @awvwgk - Looking things over, it seems with #225, #220, #248 and #254, some really nice features and a couple of important bugfixes, it would be good to do a new release.  Do you have anything in mind that needs to be done before a release?  Is there anything I can help with?

**Pull request merged**
