### PR TITLE
mkl-rt, install_rpath, install python

### PR DESCRIPTION
**Pull request by loriab**
Ported your mkl-rt option from another project. Installed rpath was returning not found without these adjustments. And the python interface wasn't installing properly in a combo exe+python build unless I moved the block.

No pressure, as I can patch as needed, but see if you want to incorporate any of these changes.

### CODE REVIEW

**Review by awvwgk — COMMENTED** [review]
This patch requires changes and releases in the dependencies first due to the changed wrap files.

**Comment by loriab** [comment]
> I don't like the rpath fixing here since it introduces the installation prefix in the rpath, also reading a bit on rpath it seems to be generally discouraged (see https://wiki.debian.org/RpathIssue).

Since libdftd4 is the not-found lib, I view it as fitting into Debian's "Currently, the only generally accepted use of this feature in Debian is to add non-standard library path (like /usr/lib/<package>) to libraries that are only intended to be used by the executables or other libraries within the same source package.". But ok, I can live without the change. Thanks for considering it.

> My preferred strategy on this is either to install and distribute in a package manager like pacman or conda, which take care of the dynamic loading of the shared objects, or to create distributions outside of a package manager to link statically. The setup in this repository should allow to statically link even the Python extension module, which is quite handy for local development:

My only hesitation with a fully static distribution is that we had some complaints about static dftd3 (Intel) built on Linux segfaulting when run under Windows Subsystem for Linux. I've got the dftd4 exe built for Linux/mkl-rt/conda dynamic libs locally. I'll try your suggestions below next, thank you.

**Comment by awvwgk** [comment]
I added an option for `mkl_rt` in a `multicharge` release and with #89 in `dftd4` as well. I would like to avoid rpath usage if possible, as explained above.

Is there anything else from this patch that should be addressed before the 3.2.0 release?

**Comment by loriab** [comment]
> I added an option for mkl_rt in a multicharge release and with #89 in dftd4 as well. I would like to avoid rpath usage if possible, as explained above.

Thank you. You didn't find the `ifcore` bit necessary? I needed it in general. But then to get a compiler-library-independent build on Linux https://github.com/dftd4/dftd4/compare/main...loriab:qcsk_mods3#diff-25739f9cf38bfde7e5ce9c4886b813ab178cbf4f037ff78b5a7f4e495860a173R47-R48, I had to patch away the `ifcore` line.

> Is there anything else from this patch that should be addressed before the 3.2.0 release?

Would you install the `parameters.toml` file, please? I'm reading it in QCEngine to fill in the big dispersion parameters table without code duplication.

How do you feel about `build_rpath`, as opposed to `install_rpath`? That was fixing some problems on Intel Mac, but easy to patch in. Would you consider leaving lines like https://github.com/dftd4/dftd4/compare/main...loriab:qcsk_mods3#diff-8f1646a4107bf72160a290989e86661c843703fd9c62cbb1eb3b2d1dd4387cc0R17-R18 with out changing the actual `library()` or `executable()` commands?

**Comment by awvwgk** [comment]
> Would you install the `parameters.toml` file, please?

Will do.

> Thank you. You didn't find the `ifcore` bit necessary? I needed it in general.

I encountered this issue with Intel 17 in `xtb` a while ago, to me the issue seems to mostly resolved since meson added the `link_language` feature. It might become problematic if you build the Python extension module together with the rest of the project. I really recommend to build the Python API separately, building both together is usually messy.

> How do you feel about `build_rpath`, as opposed to `install_rpath`? That was fixing some problems on Intel Mac, but easy to patch in.

meson should be using a build rpath by default, I don't think there is need to overwrite it manually:
```
❯ chrpath -l _build_intel_shared/app/dftd4
_build_intel_shared/app/dftd4: RPATH=$ORIGIN/..
```

But if you want to set one for the install, you can easily do so without patching the build files using:
```
❯ FC=ifort CC=icc LDFLAGS=-Wl,-rpath=\$ORIGIN/../lib meson setup _build_intel_shared --prefix=$PWD/_dist_intel_shared --libdir=lib --default-library=shared -Dlapack=mkl-rt
...
❯ ninja -C _build_intel_shared install
...
❯ chrpath -l _build_intel_shared/app/dftd4
_build_intel_shared/app/dftd4: RPATH=$ORIGIN/../lib:$ORIGIN/..
❯ chrpath -l _dist_intel_shared/bin/dftd4
_dist_intel_shared/bin/dftd4: RPATH=$ORIGIN/../lib
❯ ldd _dist_intel_shared/bin/dftd4
	linux-vdso.so.1 (0x00007ffef6792000)
	libdftd4.so.3 => /home/awvwgk/projects/src/git/mctc-tools/dftd4/_dist_intel_shared/bin/../lib/libdftd4.so.3 (0x00007fd22f490000)
	libiomp5.so => /opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libiomp5.so (0x00007fd22f089000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fd22f030000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fd22ee61000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fd22ee5a000)
	libmkl_rt.so.1 => /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_rt.so.1 (0x00007fd22e701000)
	libifcoremt.so.5 => /opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libifcoremt.so.5 (0x00007fd22e561000)
	libimf.so => /opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libimf.so (0x00007fd22ded9000)
	libsvml.so => /opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libsvml.so (0x00007fd22c360000)
	libintlc.so.5 => /opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00007fd22c0e8000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fd22c0ce000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fd22f55e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fd22bf89000)

**Comment by awvwgk** [comment]
Closing this since it is mostly addressed in 3.2.0 now

**Pull request closed without merging**
